prefix cs: <http://purl.org/vocab/changeset/schema#>

SELECT (count(?a) as ?additions) (count(?r) as ?removals) (count(?c) as ?changes)
WHERE {
{ ?a a cs:ChangeSet. FILTER EXISTS { ?a cs:addition ?b. } FILTER NOT EXISTS { ?a cs:removal ?b. } }
UNION
{ ?r a cs:ChangeSet. FILTER EXISTS { ?r cs:removal ?b. } FILTER NOT EXISTS { ?r cs:addition ?b. } }
UNION
{ ?c a cs:ChangeSet. FILTER EXISTS { ?c cs:addition ?b. ?c cs:removal ?d. } }
}
